language: php

php:
  - 5.5
  - 5.6

before_script:
  - env
  - mkdir Build; cd Build
  - >
    cat <<EOF > composer.json
    {
      "name": "typo3/neos-base-distribution",
      "config": {
          "vendor-dir": "Packages/Libraries",
          "bin-dir": "bin"
      },
      "require": {
          "typo3/neos": "1.2.*",
          "typo3/neos-nodetypes": "1.2.*",
          "typo3/neosdemotypo3org": "1.2.*",
          "typo3/neos-kickstarter": "1.2.*",
          "doctrine/migrations": "1.0.0-alpha3",
          "typo3/flow": "2.3.*",
          "moc/varnish": "dev-${TRAVIS_BRANCH}#${TRAVIS_COMMIT}"
      },
      "require-dev": {
          "typo3/buildessentials": "2.3.*",
          "mikey179/vfsstream": "1.5.*",
          "phpunit/phpunit": "4.6.*",
          "flowpack/behat": "dev-master",
          "typo3-ci/typo3flow": "dev-master"
      },
      "scripts": {
          "post-update-cmd": "TYPO3\\\\Flow\\\\Composer\\\\InstallerScripts::postUpdateAndInstall",
          "post-install-cmd": "TYPO3\\\\Flow\\\\Composer\\\\InstallerScripts::postUpdateAndInstall",
          "post-package-update": "TYPO3\\\\Flow\\\\Composer\\\\InstallerScripts::postPackageUpdateAndInstall",
          "post-package-install": "TYPO3\\\\Flow\\\\Composer\\\\InstallerScripts::postPackageUpdateAndInstall"
      }
    }
    EOF
  - cat composer.json
  - composer update --dev

script: bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/MOC.Varnish/Tests/Unit
