language: php

php:
  - 5.5
  - 5.6

before_script:
  - env
  - mkdir Build; cd Build
  - VERSION=$( if [ $TRAVIS_TAG ] ; then echo $TRAVIS_TAG ; else echo "${TRAVIS_BRANCH}.x-dev#${TRAVIS_COMMIT}" ; fi )
  - |
    cat <<EOF > composer.json
    {
      "name": "typo3/neos-base-distribution",
      "config": {
          "vendor-dir": "Packages/Libraries",
          "bin-dir": "bin"
      },
      "require": {
          "typo3/neos": "2.0.*@beta",
          "doctrine/migrations": "@dev",
          "typo3/typo3cr": "2.0.*@beta",
          "typo3/typoscript": "2.0.*@beta",
          "typo3/media": "2.0.*@beta",
          "typo3/flow": "3.0.*@beta",
          "typo3/fluid": "3.0.*@beta",
          "typo3/eel": "3.0.*@beta",
          "typo3/party": "3.0.*@beta",
          "typo3/kickstart": "3.0.*@beta",
          "moc/varnish": "${VERSION}"
      },
      "require-dev": {
          "typo3/buildessentials": "3.0.*@beta",
          "mikey179/vfsstream": "1.5.*",
          "phpunit/phpunit": "4.6.*",
          "flowpack/behat": "dev-master"
      },
      "scripts": {
          "post-update-cmd": "TYPO3\\\\Flow\\\\Composer\\\\InstallerScripts::postUpdateAndInstall",
          "post-install-cmd": "TYPO3\\\\Flow\\\\Composer\\\\InstallerScripts::postUpdateAndInstall",
          "post-package-update": "TYPO3\\\\Flow\\\\Composer\\\\InstallerScripts::postPackageUpdateAndInstall",
          "post-package-install": "TYPO3\\\\Flow\\\\Composer\\\\InstallerScripts::postPackageUpdateAndInstall"
      }
    }
  - cat composer.json 
  - composer update

script: bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/MOC.Varnish/Tests/Unit
