
MOC:
  Varnish:
    # Disables Varnish caching if set to false
    enabled: true
    # URL or URLs (if array) Varnish is running on for purge requests (skip trailing slash)
    varnishUrl: 'http://127.0.0.1'
    # Cache header sending configuration
    cacheHeaders:
      # Default and maximum TTL in seconds
      defaultSharedMaximumAge: null
      # Disable sending headers (useful for staging environments)
      disabled: false

    # Maximum length of header in bytes for requests to varnish. Used when banning. Large requests will be split across multiple smaller ones
    maximumHeaderLength: 7500

    # Port to use for reverse lookup in backend module
    reverseLookupPort: null
    # List of ignored  cache tags to skip when flushing caches by tag, e.g. 'TYPO3.Neos:Document' which is used in 'TYPO3.Neos:Menu' elements
    ignoredCacheTags: []
    # Log configuration
    log:
      backend: Neos\Flow\Log\Backend\FileBackend
      backendOptions:
        logFileURL: '%FLOW_PATH_DATA%Logs/Varnish.log'
        createParentDirectories: true
        severityThreshold: '%LOG_INFO%'
        maximumLogFileSize: 1048576
        logFilesToKeep: 1
Neos:
  Neos:
    modules:
      administration:
        submodules:
          varnish:
            label: 'Varnish cache purging'
            controller: \MOC\Varnish\Controller\VarnishCacheController
            description: 'Clear Varnish cache.'
            icon: 'fa fa-bolt'
            additionalResources:
              styleSheets:
                - 'resource://MOC.Varnish/Public/Styles/Module.css'
            privilegeTarget: 'MOC.Varnish:BackendModuleClearCache'
    fusion:
      autoInclude:
        MOC.Varnish: true
