
MOC:
  Varnish:
    enabled: true
    varnishUrl: 'http://127.0.0.1'
    cacheHeaders:
      defaultSharedMaximumAge: null
      disabled: false
    reverseLookupPort: null
    ignoredCacheTags: {  }
    log:
      backend: TYPO3\Flow\Log\Backend\FileBackend
      backendOptions:
        logFileURL: '%FLOW_PATH_DATA%Logs/Varnish.log'
        createParentDirectories: true
        severityThreshold: '%LOG_INFO%'
        maximumLogFileSize: 1048576
        logFilesToKeep: 1
TYPO3:
  Neos:
    modules:
      administration:
        submodules:
          varnish:
            label: 'Varnish cache purging'
            controller: \MOC\Varnish\Controller\VarnishCacheController
            description: 'Clear Varnish cache.'
            icon: icon-gear
            additionalResources:
              styleSheets:
                - 'resource://MOC.Varnish/Public/Styles/Module.css'
            privilegeTarget: 'MOC.Varnish:BackendModuleClearCache'
    typoScript:
      autoInclude:
        MOC.Varnish: true
